pipeline:
  name: webhook-test
  identifier: webhooktest
  projectIdentifier: Dummyproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: c1
        identifier: c1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_2
                  identifier: Wait_1
                  spec:
                    duration: 12m
        tags: {}
